test/cancel-race: get rid of write-only variables
clang rightfully complains that:

cancel-race.c:44:6: error: variable 'op_completions' set but not used [-Werror,-Wunused-but-set-variable]
   44 |         int op_completions = 0;
      |             ^
cancel-race.c:45:6: error: variable 'cancel_completions' set but not used [-Werror,-Wunused-but-set-variable]
   45 |         int cancel_completions = 0;
      |             ^

so kill them off.

Fixes: 5445d6b41ca6 ("test: add cancel-vs-completion race stress test")
Signed-off-by: Jens Axboe <axboe@kernel.dk>