test/timeout-overflow: Fix `-Werror=maybe-uninitialized`
Fix this:
```
  In file included from timeout-overflow.c:12:
  timeout-overflow.c: In function ‘test_timeout_overflow’:
  ../src/include/liburing.h:406:9: error: ‘num’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    406 |         io_uring_prep_rw(IORING_OP_TIMEOUT, sqe, -1, ts, 1, count);
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  timeout-overflow.c:104:26: note: ‘num’ was declared here
    104 |                 unsigned num;
        |                          ^~~
```

Fixes: a4b465536021ee9c4d6d450a9461ddfc116d08b1 ("Add test for overflow of timeout request's sequence")
Cc: yangerkun <yangerkun@huawei.com>
Signed-off-by: Ammar Faizi <ammar.faizi@students.amikom.ac.id>
Link: https://lore.kernel.org/r/BULrcXMbevM-ammarfaizi2@gnuweeb.org
Signed-off-by: Jens Axboe <axboe@kernel.dk>