test/submit-reuse: Fix `-Wunused-but-set-variable` warning from clang-15
clang-15 correctly warns:
```
  submit-reuse.c:29:6: error: variable 'i' set but not used \
  [-Werror,-Wunused-but-set-variable]
          int i = 0;
            ^
  1 error generated.
  make[1]: *** [Makefile:210: submit-reuse.t] Error 1
```
Remove the i variable here, it's not used.

Fixes: ad543701a816d0d84383a8aafb1ce27ee2f93053 ("Add test case for -EFAULT triggered by iov reuse")
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>