test/35fa71a030ca: Fix `-Wunused-but-set-variable` warning from clang-15
clang-15 correctly warns:
```
  35fa71a030ca.c:241:7: error: variable 'iter' set but not used \
  [-Werror,-Wunused-but-set-variable]
    int iter;
        ^
  1 error generated.
  make[1]: *** [Makefile:210: 35fa71a030ca.t] Error 1
```
Remove the iter variable here, it's not used.

Fixes: 78f59df3339191a500d9a27e2fe9d2eea888a2e0 ("Add regression test cases for three recent issues")
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>