The io_uring.7 manpage has an example that uses the "errno" variable. This variable is not known and leads to a compiler error, due to a missing #include <errno.h>. Add it to get the example compiled.
Contact: Hubert Feyrer <hubertf@gmx.de>

=== BEFORE ===

$ gcc 4manpage-original.c  -o 4manpage-original
4manpage-original.c: In function ‘io_uring_setup’:
4manpage-original.c:44:25: error: ‘errno’ undeclared (first use in this function)
   44 |     return (ret < 0) ? -errno : ret;
      |                         ^~~~~
4manpage-original.c:15:1: note: ‘errno’ is defined in header ‘<errno.h>’; this is probably fixable by adding ‘#include <errno.h>’
   14 | #include <linux/io_uring.h>
  +++ |+#include <errno.h>
   15 |
4manpage-original.c:44:25: note: each undeclared identifier is reported only once for each function it appears in
   44 |     return (ret < 0) ? -errno : ret;
      |                         ^~~~~
4manpage-original.c: In function ‘io_uring_enter’:
4manpage-original.c:53:25: error: ‘errno’ undeclared (first use in this function)
   53 |     return (ret < 0) ? -errno : ret;
      |                         ^~~~~
4manpage-original.c:53:25: note: ‘errno’ is defined in header ‘<errno.h>’; this is probably fixable by adding ‘#include <errno.h>’

==== PATCH ===

$ diff -u 4manpage-original.c 4manpage.c
--- 4manpage-original.c	2025-12-06 11:52:24.171027464 +0100
+++ 4manpage.c	2025-12-06 11:32:55.431256160 +0100
@@ -10,6 +10,7 @@
 #include <unistd.h>
 #include <string.h>
 #include <stdatomic.h>
+#include <errno.h>

 #include <linux/io_uring.h>

=== AFTER ===

$ gcc 4manpage.c -o 4manpage
$ cat 4manpage.c | ./4manpage | diff -u 4manpage.c -
$

Signed-off-by: Hubert Feyrer <hubertf@gmx.de>