test: Compile nolibc.c only when CONFIG_NOLIBC is set
building nolibc.c fails for non nolibc targets

Fixes
In file included from nolibc.c:33:
./../src/lib.h:20:2: error: "This arch doesn't support building liburing without libc"
   20 | #error "This arch doesn't support building liburing without libc"
      |  ^
1 error generated.

Signed-off-by: Khem Raj <raj.khem@gmail.com>