barrier.h: add generic smp_mb implementation
This missing define causes build failures on s390:

  src/include/liburing.h:298: undefined reference to `io_uring_smp_mb'

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Jens Axboe <axboe@kernel.dk>