arch/generic: Rename `____sys_io_uring*` to `__sys_io_uring*`
In commit:

  4aa1a8aefc3dc3875621c64cef0087968e57181d ("Delete src/syscall.c and get back to use __sys_io_uring* functions")

I forgot to rename `____sys_io_uring*` to `__sys_io_uring*` in
arch/generic. This results in build error on archs other than
aarch64 and x86-64:

  error: implicit declaration of function `__sys_io_uring*`;

Rename `____sys_io_uring*` to `__sys_io_uring*`.
Thanks to the GitHub bot who spotted the issue quickly!

Fixes: 4aa1a8aefc3dc3875621c64cef0087968e57181d ("Delete src/syscall.c and get back to use __sys_io_uring* functions")
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>
Link: https://lore.kernel.org/r/20220721155139.760436-1-ammarfaizi2@gnuweeb.org
Signed-off-by: Jens Axboe <axboe@kernel.dk>