Fix potential compilation error due to io_uring_for_each_cqe macro
In 1c1c806ff4e1 ("Add struct io_uring_cqe_iter") the body of the
io_uring_for_each_cqe macro was changed to use io_uring_cqe_iter and
its 'head' member. However, the '.head' use site in the macro's body
clashes with the macro's 'head' argument. This leads to compilation
errors if the macro is invoked with something else as 'head' as second
argument.

For example, Samba uses the macro as follows:

io_uring_for_each_cqe(&config->uring, cqhead, cqe) {
   …
}

which results in

In file included from ../../source3/modules/vfs_io_uring.c:49:
../../source3/modules/vfs_io_uring.c: In function ‘_vfs_io_uring_queue_run’:
../../source3/modules/vfs_io_uring.c:297:47: error: ‘struct io_uring_cqe_iter’ has no member named ‘cqhead’; did you mean ‘head’?
  297 |         io_uring_for_each_cqe(&config->uring, cqhead, cqe) {

as reported in https://bugs.gentoo.org/956879

Fixes: 1c1c806ff4e1d2a122180612d5d75cf648a33211
Signed-off-by: Florian Schmaus <flo@geekplace.eu>