examples/io_uring-udp: Use a proper cast for `(struct sockaddr *)` argument
Sometimes the compiler accepts `(struct sockaddr_in *)` and
`(struct sockaddr_in6 *)` to be passed in to `(struct sockaddr *)`
without a cast. But not all compilers agree with that. Building with
clang 13.0.1 yields the following errors:

    io_uring-udp.c:134:18: error: incompatible pointer types passing \
    'struct sockaddr_in6 *' to parameter of type 'const struct sockaddr *' \
    [-Werror,-Wincompatible-pointer-types

    io_uring-udp.c:142:18: error: incompatible pointer types passing \
    'struct sockaddr_in *' to parameter of type 'const struct sockaddr *' \
    [-Werror,-Wincompatible-pointer-types]

Explicitly cast the pointer to (struct sockaddr *) to avoid this error.

Cc: Dylan Yudaken <dylany@fb.com>
Cc: Facebook Kernel Team <kernel-team@fb.com>
Fixes: 61d472b51e761e61cbf46caea40aaf40d8ed1484 ("add an example for a UDP server")
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>
Link: https://lore.kernel.org/r/20220726164310.266060-1-ammar.faizi@intel.com
Signed-off-by: Jens Axboe <axboe@kernel.dk>