examples/proxy: fix anal CI fallout
proxy.c: In function ‘close_conn’:
248
proxy.c:505:37: error: unused parameter ‘c’ [-Werror=unused-parameter]
249
505 | static void close_conn(struct conn *c, struct conn_dir *cd)
250
    |                        ~~~~~~~~~~~~~^

Rename it to close_cd() and get rid of the unused argument.

Signed-off-by: Jens Axboe <axboe@kernel.dk>