examples,test: Remove unused linux/errqueue.h
This header is not needed therefore remove it, this cleanup also helps
compiling on musl/clang

/usr/include/linux/errqueue.h:57:20: error: array has incomplete element typ
e 'struct timespec'
        struct timespec ts[3];
                          ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>